apiVersion: v1
kind: Service
metadata:
  name: php-nginx
  labels:
    app: architrave
spec:
  ports:
    - port: 80
      port: 443
  selector:
    app: architrave
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: php-nginx
  labels:
    app: architrave
spec:
  selector:
    matchLabels:
      app: architrave
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: architrave
        tier: frontend
    spec:
      volumes:
      # Create the shared files volume to be used in both pods
      - name: shared-files
        emptyDir: {}
      containers:
      - image: titanlien/architrave-php:20181117080950
        name: php
        volumeMounts:
          - name: shared-files
            mountPath: /var/www/html
      - image: titanlien/architrave-web:20181117080847
        name: nginx
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
          - name: shared-files
            mountPath: /var/www/html
